org.gradle.jvmargs=-Xmx3g -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Disable file watching for container and sandbox compatibility.
org.gradle.vfs.watch=false
android.useAndroidX=true
android.nonTransitiveRClass=true

# Add x86_64 for emulator builds; this also controls the Go AAR and APK splits.
netbootAbis=arm64-v8a,armeabi-v7a

org.gradle.tooling.parallel=true
